### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by axeforeverjumo** [weibeld/Simple-Tweets#3]
I don't know what i need to do, i build apk, not editing nothing else that "adding a compile in gradle", and then just builded the apk. Do I need to change something more? what i am doing wrong, the app crash when I go to the Twitter Web to authorize my app, then when redirect to the app, the app crash and crash all timee...
Please help me.

**Comment by weibeld** [comment]
Can you post the logs when the app crashes?

Just run:

~~~bash
adb -d logcat
~~~

when your physical phone is connected by USB and then start the app.

**Comment by axeforeverjumo** [comment]
This appears in the Event Log Window (Android Studio)
> 10:56	Executing tasks: [:app:assembleDebug]
> 
> 10:57	Gradle build finished with 1 error(s) and 2 warning(s) in 42s 176ms
> 
> 11:03	Adb connection Error:EOF
> 
> 11:03	Connection attempts: 1
> 
> 11:03	Connection attempts: 2
> 
> 11:03	Connection attempts: 3

And this in the Logcat Windows (Android Studio):

> 02-07 11:08:27.746 3909-3909/? D/ViewRootImpl@2781237[TimelineActivity]: dispatchAttachedToWindow
> 02-07 11:08:27.751 3909-3909/? D/AndroidRuntime: Shutting down VM
> 02-07 11:08:27.752 3909-3909/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                  Process: org.weibeld.simpletweets, PID: 3909
>                                                  org.greenrobot.eventbus.EventBusException: Subscriber class org.weibeld.simpletweets.fragments.HomeTimelineFragment and its super classes have no public methods with the @Subscribe annotation
>                                                      at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
>                                                      at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
>                                                      at org.weibeld.simpletweets.fragments.TimelineFragment.onCreate(TimelineFragment.java:132)
>                                                      at android.support.v4.app.Fragment.performCreate(Fragment.java:2177)
>                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
>                                                      at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1080)
>                                                      at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:971)
>                                                      at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
>                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
>                                                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
>                                                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1979)
>                                                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
>                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
>                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
>                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
>                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
>                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                      at com.android.internal.policy.DecorView.onMeasure(DecorView.java:849)
>                                                      at android.view.View.measure(View.java:21045)
>                                                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2576)
>                                                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1635)
>                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
>                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
>                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
>                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
>                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:702)
>                                                      at android.view.Choreographer.doFrame(Choreographer.java:638)
> 02-07 11:08:27.752 3909-3909/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
>                                                      at android.os.Handler.handleCallback(Handler.java:751)
>                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                      at android.os.Looper.loop(Looper.java:154)
>                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
>                                                      at java.lang.reflect.Method.invoke(Native Method)
>                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
> 
> > 
when i run on terminal (Ubuntu) adb -d logcat i have too much information, even my alarm app, :/.

**Comment by axeforeverjumo** [comment]
> 02-07 11:21:25.970 7740-7740/org.weibeld.simpletweets W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
> 02-07 11:21:26.050 7740-7740/org.weibeld.simpletweets D/ViewRootImpl@a4e5336[TimelineActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 84 - 0, 0) vi=Rect(0, 84 - 0, 0) or=1
> 02-07 11:21:26.571 7740-7740/org.weibeld.simpletweets V/AsyncHttpRH: Progress 1224 from 521 (235%)
> 02-07 11:21:26.615 7740-7740/org.weibeld.simpletweets V/AsyncHttpRH: Progress 2 from 28 ( 7%)
> 02-07 11:21:26.630 7740-7740/org.weibeld.simpletweets W/FlowLog: Failed to open file
>                                                                  java.io.FileNotFoundException: SimpleTweetsDatabase.db
>                                                                      at android.content.res.AssetManager.openAsset(Native Method)
>                                                                      at android.content.res.AssetManager.open(AssetManager.java:423)
>                                                                      at android.content.res.AssetManager.open(AssetManager.java:397)
>                                                                      at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:127)
>                                                                      at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.performRestoreFromBackup(DatabaseHelperDelegate.java:44)
>                                                                      at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.performRestoreFromBackup(FlowSQLiteOpenHelper.java:33)
>                                                                      at com.raizlabs.android.dbflow.config.DatabaseDefinition.getHelper(DatabaseDefinition.java:201)
>                                                                      at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:207)
>                                                                      at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:226)
>                                                                      at org.weibeld.simpletweets.models.Tweet.deleteTimelineTweets(Tweet.java:70)
>                                                                      at org.weibeld.simpletweets.fragments.HomeTimelineFragment$1.onSuccess(HomeTimelineFragment.java:55)
>                                                                      at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:154)
>                                                                      at android.os.Handler.handleCallback(Handler.java:751)
>                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                      at android.os.Looper.loop(Looper.java:154)
>                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
>                                                                      at java.lang.reflect.Method.invoke(Native Method)
>                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
> 02-07 11:21:26.660 7740-7740/org.weibeld.simpletweets V/AsyncHttpRH: Progress 2 from 28 ( 7%)
>

**Comment by axeforeverjumo** [comment]
(Now is working but actually i am not doing nothing i have 2 warnings. just it....
