### ISSUE TITLE
retrolambda debug-0 ERROR

### ISSUE THREAD

**Issue by axeforeverjumo** [weibeld/Simple-Tweets#4]
Any error with retrolambda debug-0, you need to upgrade your retrolambda, in my case 2018/02/07 is the:
> retrolambda 3.7.0
so to upgrade just change it in your gradle, in my case like this:
`me.tatarka:gradle-retrolambda:3.7.0`
sync your proyect againg and it's going to be solved.

**Comment by weibeld** [comment]
Does it work with the updated Retrolambda?

**Comment by axeforeverjumo** [comment]
Yes, its working good
